export const ErrorCodes = {
    INVALID_REQUEST: 'INVALID_REQUEST',
    UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    SQL_ERROR: 'SQL_ERROR',
    FAILED_TO_FETCH: 'FAILED_TO_FETCH',
} as const;
