export const ErrorCodes = {
    TOKEN_MISSING: 'TOKEN_MISSING',
    COOKIE_SET_FAILED: 'COOKIE_SET_FAILED',
    COOKIE_DELETE_FAILED: 'COOKIE_DELETE_FAILED',
    SQL_ERROR: 'SQL_ERROR',
    INVALID_REQUEST: 'INVALID_REQUEST',
    FAILED_TO_FETCH: 'FAILED_TO_FETCH',
} as const;
