export const ErrorCodes = {
    INVALID_REQUEST: 'INVALID_REQUEST',
    UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
    CREATE_SESSION_FAILED: 'CREATE_SESSION_FAILED',
    DELETE_SESSION_FAILED: 'DELETE_SESSION_FAILED',
    UNAUTHORIZED: 'UNAUTHORIZED',
    UNKNOWN_ERROR: 'UNKNOWN_ERROR',
    SQL_ERROR: 'SQL_ERROR',
    NO_AVAILABLE_IP: 'NO_AVAILABLE_IP',
    FAILED_TO_FETCH: 'FAILED_TO_FETCH',
} as const;
