services:

  rploxy:
    build:
      dockerfile: ./Dockerfile.rploxy
    ports:
      - "80:80/tcp"
      - "443:443/tcp"

  app:
    build:
      dockerfile: ./Dockerfile.app.prod
    ports:
      - "3000:3000/tcp"
      - "51820:51820/udp" # ホスト側のポート:コンテナ内のポート
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
