services:
  wg-test-prod:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "51820:51820/udp"
      - "8080:8080/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      # For `XXXXXXXX`, specify any string that is difficult to guess.
      - SECRET_API_KEY=XXXXXXXX
