services:
  wg-test-dev:
    build:
      dockerfile: ./Dockerfile.dev
    volumes:
      - ./src/:/app/
      - temp:/app/node_modules/
    ports:
      - "51820:51820/udp"
      - "3000:3000/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env

volumes:
  temp:
    driver: local
