services:
  wg-test-prod:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "51820:51820/udp"
      - "3000:3000/tcp"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    env_file:
      - .env
